name: Release to NPM

on:
  push:
    branches: [main]

jobs:
  test-release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
